version: '3.8'

services:
  frontend:
    build: ./frontend-app
    ports:
      - "5173:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bicara-network

  backend:
    build: ./backend-app
    ports:
      - "3000:3000"
    env_file:
      - ./backend-app/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bicara-network

networks:
  bicara-network:
    driver: bridge
